### PR TITLE
Initial draft for reproducible research

### PR DESCRIPTION
**Pull request by Vathasav**
I have created some initial draft for the reproducible research session. Still lot of work has to be done.

### CODE REVIEW

**Comment by wikfeldt** [comment]
This material looks great, but should we not create an independent lesson about reproducible research?

**Comment by wikfeldt** [comment]
If in a separate lesson, we could even include a discussion/demo/hands-on on other tools, e.g. for workflow automation/management with e.g. sumatra (http://sumatra.readthedocs.io/en/0.7.3/)

**Comment by bast** [comment]
I agree that it should be a separate lesson.

**Comment by bast** [comment]
And +1 for discussing Sumatra - cool!

**Comment by wikfeldt** [comment]
reproducibility is now an independent lesson, so closing this

**Pull request closed without merging**
